name: Flutter CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-test-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install prerequisites
        run: |
          sudo apt-get update -y && sudo apt-get upgrade -y
          sudo apt-get install -y curl git unzip xz-utils zip libglu1-mesa apt-transport-https

      - name: Install Dart 3.9 via apt-get
        run: |
          wget -qO- https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo gpg --dearmor -o /usr/share/keyrings/dart.gpg
          echo 'deb [signed-by=/usr/share/keyrings/dart.gpg arch=amd64] https://storage.googleapis.com/download.dartlang.org/linux/debian stable main' | sudo tee /etc/apt/sources.list.d/dart_stable.list
          sudo apt-get update
          sudo apt-get install -y dart

      - name: Setup Flutter SDK 3.35.6 (stable)
        run: |
          FLUTTER_DIR="$HOME/flutter"
          mkdir -p $FLUTTER_DIR
          curl -L -o flutter_linux_3.35.6-stable.tar.xz https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_3.35.6-stable.tar.xz
          tar -xf flutter_linux_3.35.6-stable.tar.xz -C $FLUTTER_DIR
          echo "$FLUTTER_DIR/flutter/bin" >> $GITHUB_PATH
          flutter --version
          dart --version

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze code
        run: flutter analyze

      #- name: Run tests
      #  run: flutter test

      - name: Get next version
        id: version
        run: |
          LATEST=$(git tag --sort=-v:refname | head -n 1)
          if [[ -z "$LATEST" ]]; then
            NEXT="1.0"
          else
            MAJOR=$(echo $LATEST | cut -d. -f1)
            MINOR=$(echo $LATEST | cut -d. -f2)
            if [[ "$MINOR" -ge 9 ]]; then
              MAJOR=$((MAJOR + 1))
              MINOR=0
            else
              MINOR=$((MINOR + 1))
            fi
            NEXT="$MAJOR.$MINOR"
          fi
          echo "next=$NEXT" >> $GITHUB_OUTPUT
          echo "Next version: $NEXT"

      - name: Update pubspec.yaml version
        run: |
          sed -i "s/^version:.*/version: ${{ steps.version.outputs.next }}+1/" pubspec.yaml
          echo "Updated pubspec.yaml to version ${{ steps.version.outputs.next }}"

      - name: Build release APK
        run: flutter build apk --release

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.version.outputs.next }}
          name: "Flutter Release ${{ steps.version.outputs.next }}"
          body: |
            Flutter release version ${{ steps.version.outputs.next }}
            Tests, analysis, and build completed successfully.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload APK to release
        uses: softprops/action-gh-release@v2
        with:
          files: build/app/outputs/flutter-apk/app-release.apk
          tag_name: ${{ steps.version.outputs.next }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
