name: Flutter CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-test-release:
    runs-on: ubuntu-latest

    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'

      # Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # Analyze & test
      - name: Analyze code
        run: flutter analyze

      #- name: Run tests
      #  run: flutter test

      # Determine next version number
      - name: Get next version
        id: version
        run: |
          # Get the latest tag (like 1.0, 1.1, etc.)
          LATEST=$(git tag --sort=-v:refname | head -n 1)
          if [[ -z "$LATEST" ]]; then
            NEXT="1.0"
          else
            MAJOR=$(echo $LATEST | cut -d. -f1)
            MINOR=$(echo $LATEST | cut -d. -f2)
            if [[ "$MINOR" -ge 9 ]]; then
              MAJOR=$((MAJOR + 1))
              MINOR=0
            else
              MINOR=$((MINOR + 1))
            fi
            NEXT="$MAJOR.$MINOR"
          fi
          echo "next=$NEXT" >> $GITHUB_OUTPUT
          echo "Next version: $NEXT"

      # Update version in pubspec.yaml
      - name: Update pubspec.yaml version
        run: |
          sed -i "s/^version:.*/version: ${{ steps.version.outputs.next }}+1/" pubspec.yaml
          echo "Updated pubspec.yaml to version ${{ steps.version.outputs.next }}"

      # Build release APK
      - name: Build release APK
        run: flutter build apk --release

      # Create GitHub Release
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.version.outputs.next }}
          name: "Flutter Release ${{ steps.version.outputs.next }}"
          body: |
            Flutter release version ${{ steps.version.outputs.next }}
            Tests, analysis, and build completed successfully.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Upload APK to release
      - name: Upload APK
        uses: softprops/action-gh-release@v2
        with:
          files: build/app/outputs/flutter-apk/app-release.apk
          tag_name: ${{ steps.version.outputs.next }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
