name: Flutter CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-test-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Dart 3.9+
        run: |
          wget https://storage.googleapis.com/download.dartlang.org/linux/debian/dart_3.9.0-1_amd64.deb
          sudo dpkg -i dart_3.9.0-1_amd64.deb
          sudo apt-get update
          sudo apt-get install -f

      - name: Setup Flutter SDK
        uses: flutter-actions/setup-flutter@v4
        with:
          channel: stable
          version: 3.13.4

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze code
        run: flutter analyze

      - name: Get next version
        id: version
        run: |
          LATEST=$(git tag --sort=-v:refname | head -n 1)
          if [[ -z "$LATEST" ]]; then
            NEXT="1.0"
          else
            MAJOR=$(echo $LATEST | cut -d. -f1)
            MINOR=$(echo $LATEST | cut -d. -f2)
            if [[ "$MINOR" -ge 9 ]]; then
              MAJOR=$((MAJOR + 1))
              MINOR=0
            else
              MINOR=$((MINOR + 1))
            fi
            NEXT="$MAJOR.$MINOR"
          fi
          echo "next=$NEXT" >> $GITHUB_OUTPUT
          echo "Next version: $NEXT"

      - name: Update pubspec.yaml version
        run: |
          sed -i "s/^version:.*/version: ${{ steps.version.outputs.next }}+1/" pubspec.yaml
          echo "Updated pubspec.yaml to version ${{ steps.version.outputs.next }}"

      - name: Build release APK
        run: flutter build apk --release

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.version.outputs.next }}
          name: "Flutter Release ${{ steps.version.outputs.next }}"
          body: |
            Flutter release version ${{ steps.version.outputs.next }}
            Tests, analysis, and build completed successfully.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload APK
        uses: softprops/action-gh-release@v2
        with:
          files: build/app/outputs/flutter-apk/app-release.apk
          tag_name: ${{ steps.version.outputs.next }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
