name: Flutter CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-test-release:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Install SDKs (Flutter & Dart)
      - name: Setup Flutter & Dart
        run: |
          # Install Dart
          wget -qO- https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo gpg --dearmor -o /usr/share/keyrings/dart.gpg
          echo 'deb [signed-by=/usr/share/keyrings/dart.gpg arch=amd64] https://storage.googleapis.com/download.dartlang.org/linux/debian stable main' | sudo tee /etc/apt/sources.list.d/dart_stable.list
          sudo apt-get install -y dart > /dev/null 2>&1
          
          # Install Flutter
          FLUTTER_DIR="$HOME/flutter"
          mkdir -p $FLUTTER_DIR
          wget https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_3.35.6-stable.tar.xz -O flutter.tar.xz > /dev/null 2>&1
          tar -xf flutter.tar.xz -C $FLUTTER_DIR --strip-components=1 > /dev/null 2>&1
          
          # Update PATH for current step
          export PATH="$FLUTTER_DIR/bin:$PATH"
          
          # Show versions
          flutter --version
          dart --version

      # Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # Analyze code
      - name: Analyze code
        run: flutter analyze --no-fatal-infos --no-fatal-warnings

      # Build release APK
      - name: Build release APK
        run: flutter build apk --release

      # Create GitHub Release
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.sha }}
          name: "Flutter Release ${{ github.sha }}"
          body: "Flutter release for commit ${{ github.sha }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Upload APK to release
      - name: Upload APK
        uses: softprops/action-gh-release@v2
        with:
          files: build/app/outputs/flutter-apk/app-release.apk
          tag_name: ${{ github.sha }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
